# -*- coding: utf-8 -*-
"""Compression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fyYYo2rZQ3Muv6ckBnlyZaDAXPZivYo0
"""

import numpy as np
import matplotlib.pyplot as plt

# Given data
dataset = [
    91505,  98135,  109433, 121779, 138858,
    159324, 179051, 203916, 236099, 270114,
    304109, 364048, 412313, 465041, 512564,
    561994, 634886, 701588, 788286, 812935,
    771724, 932470, 999642
]

years = [
    2000, 2001, 2002, 2003, 2004,
    2005, 2006, 2007, 2008, 2009,
    2010, 2011, 2012, 2013, 2014,
    2015, 2016, 2017, 2018, 2019,
    2020, 2021, 2022,
]

# Reshape data
X = np.array(years)
y = np.array(dataset)

# Fit a polynomial of degree 1 (linear regression)
coefficients = np.polyfit(X, y, deg=50)

# Print the coefficients
print("Slope (Coefficients):", coefficients)

# Make predictions for the given years
pred_X = np.array([2021,2022,2023,2024,2025,])
pred_Y = np.polyval(coefficients, pred_X)

print(pred_X, pred_Y)

# Plot the actual vs. predicted values
plt.scatter(X, y, color='blue', label='Actual')
plt.plot(X, y, color='blue', linewidth=3, label='Actual')
plt.plot(pred_X, pred_Y, color='green', linewidth=3, label='Predicted')
plt.scatter(pred_X, pred_Y, color='green', label='Predicted')
plt.xlabel('Year')
plt.ylabel('Dataset Values')
plt.title('Polynomial Regression Prediction (Degree 1)')
plt.legend()
plt.show()